---
title: "Senior Thesis"
author: "Theophilus Bose"
date: "2026-09-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(srvyr)
library(mice)
```

```{r Loading the Dataset}
rhfs <- read.csv("RHFS_2024_Public_Variables.csv")

# Turning Categorical Variables into Factors
rhfs <- rhfs |> 
  mutate(
    across(
      c(NUMCAT_R, OUTCOME, PROPCON, PROPTOWN,
        COMPLEX, NUMBLD_R, YRNEWBLG_R, YRPROPACQ_R, APPRWAIVER,
        CASHDWN, HOWACQ, HOWMVAL, OFFSTPARKAHS, UNITSTAT,
        ADAGENCY, ADAGENT, ADNEWSPAPER, ADONLINE, ADOTHONLINE,
        ADVERTISE, ADWEBSITE, MLS, MNGMNT, NUMOTHPROP,
        NUMOTHUNITS, OWNENT, OWNOTHPROP, COMMSPACE, CONCSS,
        ICABLE, IELEC, IGAS, IPARKING, IPOOL,
        ISEWER, ITRASH, IWATER, IWIFI, LEASLNG,
        LNGTRMPRV, NORNTAPPFEE, PAYAPP, PAYCASH, PAYCHK,
        PAYCREDIT, PAYONLINE, PAYOTH, PAYTHIRD, RCONTROLAHS,
        RECCOMMREN, RNTAPPFEEWAIV, SECDEPAMT, SENIOR, WEEKLNG,
        OPTAX_R, PROPANS, ACCEPT, BENEOTH, ECONDEVLP,
        ELDERLY, GOVBELOW, GOVGRANT, HISTORIC, LOWINAREA,
        LOWINCTEN, OTHRCV, RSUBSIDY, STLOWINC, YRMORT_R,
        DEBT, DEBT1, GREENMORT, LOCTYP, MORTGET,
        PMTFREQ, REGPAY, RPIPMI, RPIPRIN, RPIPRPINS,
        RPIPRPTAX, WHYNOMRT, SAMPSTRATA, MORTAMT_R, OUTBAL_R, RNTAPPFEE_R, 
        YRPROPREHAB_R), 
      as.factor
    )
   )

# Renaming some factor levels for later convenience
rhfs <- rhfs |> 
  mutate(
    NUMCAT_R = fct_recode(
      NUMCAT_R, 
      "1 Unit" = "0", 
      "2-4 Units" = "1", 
      "5-24 Units" = "2", 
      "25-49 Units" = "3", 
      "50+ Units" = "4"
    ), 
    OUTCOME = fct_recode(
      OUTCOME, 
      "Interview Compl; self response" = "1", 
      "Assisted living limited interview; self response" = "3", 
      "Conversion from partial to full interview" = "5", 
      "Interview Compl; field interview" = "201", 
      "Assisted living limited interview; field interview" = "203", 
      "Sufficient partial; field interview" = "204", 
      "Military limited field interview" = "206"
    )
  )

# Rearranging variables greatly improves View(rhfs)
questionnaire_order <- c(
  # 1c-1e and property definition
  "PROPTOWN", "PROPCON", "COMPLEX",
  "NUMBLD_R", "NUMUNITS_R", "NUMCAT_R", 

  # 2-4e
  "UNITSTAT", "YRNEWBLG_R", "HOWACQ", "YRPROPACQ_R", "PURPRICE_R",
  "CASHDWN", "CASHDWNAMT", "MRKTVAL_R", "HOWMVAL", "APPRWAIVER",

  # 5-6: occupancy, rents, and rent payment methods
  "BROOMS", "TOTRENTVAC", "TRENOC_R", "TRENVA_R", "TOWNOC_R",
  "TEMPOC_R", "TOTHVA_R", "LOWRENT", "HIRENT", "RENT",
  "RENTNO_R", "RENTLT249_R", "RENT274_R", "RENT299_R", "RENT349_R",
  "RENT399_R", "RENT449_R", "RENT499_R", "RENT549_R", "RENT599_R",
  "RENT649_R", "RENT699_R", "RENT749_R", "RENT799_R", "RENT899_R",
  "RENT999_R", "RENT1099_R", "RENT1249_R", "RENT1499_R", "RENT1999_R",
  "RENT2499_R", "RENT2999_R", "RENT3499_R", "RENT3999_R", "RENT4499_R",
  "RENT4999_R", "RENT5000_R", "BED0_R", "BED1_R", "BED2_R", "BED3_R",
  "PAYONLINE", "PAYTHIRD", "PAYAPP", "PAYCREDIT", "PAYCHK", "PAYCASH", "PAYOTH",

  # 6a-11c
  "LEASLNG", "LNGTRMPRV", "WEEKLNG", "WEEKLNGNUM", "WEEKLNGPCT",
  "RNTAPPFEE_R", "NORNTAPPFEE", "RNTAPPFEEWAIV", "PCTFEEWAIV_R", "SECDEPAMT",
  "CONCSS", "CONCSSNUM", "SENIOR", "RCONTROL", "RCONTROLAHS",
  "OFFSTPARK", "OFFSTPARKAHS", "IELEC", "IGAS", "IWATER", "ISEWER", "ITRASH",
  "ICABLE", "IWIFI", "IPOOL", "IPARKING", "PROPANS",

  # 12a-15e
  "TOTCOLL", "COMMSPACE", "RECCOMMREN", "COMMRENT", "MNGMNT", "HRSMNGMNT",
  "ADVERTISE", "ADWEBSITE", "ADONLINE", "ADOTHONLINE", "ADNEWSPAPER",
  "ADAGENCY", "ADAGENT", "MLS",

  # 16: operating expenses
  "OPPAY", "OPTAX_R", "OPINSUR", "OPELGAS", "OPWTRSWR", "OPREP", "OPMNG",
  "OPPROTH", "OPSECUR", "OPLAND", "OPOTHEX", "OPEX_R",

  # 17-18c: capital expenses and ownership
  "CAPEX_R", "CPHEATAMT", "CPRFAMT", "CPWINAMT", "CPDOORAMT", "CPFLRAMT",
  "CPEXTAMT", "CPPLBAMT", "CPELEAMT", "CPKITAMT", "CPBATAMT", "CPACCAMT",
  "CPOTHAMT", "CPRESAMT_R", "OWNENT", "OWNOTHPROP", "NUMOTHPROP", "NUMOTHUNITS",

  # 19-23: subsidies, tax credits, and tax reductions
  "HUDUNITS", "GOVBELOW", "RSUBSIDY", "ELDERLY", "GOVGRANT", "BENEOTH",
  "LIHTCUNITS", "STLOWINC", "HISTORIC", "LOWINCTEN", "LOWINAREA", "ECONDEVLP", "OTHRCV",

  # 24-37: debt/mortgage section and HUD voucher history
  "DEBT", "WHYNOMRT", "DEBTNUM", "DEBT1", "YRMORT_R", "MORTAMT_R", "OUTBAL_R",
  "APPVAL_R", "GREENMORT", "MORTGET", "LOCTYP", "REGPAY", "PMTAMT_R", "PMTFREQ",
  "RPIPRIN", "RPIPRPINS", "RPIPMI", "RPIPRPTAX", "ACCEPT"
)

rhfs <- rhfs |>
  relocate(
    CONTROLPUF, OUTCOME, SAMPSTRATA, SURVYR,
    all_of(questionnaire_order)
  ) |>
  # Keep the full-sample and replicate weights together at the far right.
  relocate(
    WEIGHT, starts_with("REPWGT"), .after = last_col()
  )
```

```{r Survey Data Setup}
# Loads the data frame with srvyr
df <- rhfs |> 
  select(-REPWGT0) |> # REPWGT0 is equivalent to WEIGHT
  as_survey_rep(
    repweights = starts_with("REPWGT"), 
    weights = WEIGHT, 
    type = "successive-difference", 
    combined_weights = TRUE, 
    # Decided to set to T to follow SDR as outlined by Ash (to match what was
    # done in Census's Methodology)
    mse = TRUE
  )

# Sanity check for if the data was successfully loaded with srvyr
# using Table 5 of Census's RHFS Methodology
df |> 
  summarize(
    properties = survey_total(vartype = "se") # Applies weights and calculates se of properties
  ) |> 
  mutate( # Dividing by 1000 to match Table 5's scale
    properties = properties / 1000, 
    properties_se = properties_se / 1000, 
    moe = properties_se * 1.645 # 90% margin of error
  )
```

```{r Cleaning the Dataset}
# Makes View(rhfs) much more productive.
rhfs <- rhfs |> 
  select(-starts_with("REPWGT"), -WEIGHT, 
         -SURVYR, -CONTROLPUF, # is always 2024, ID isn't useful in data analysis
         # J flag variables mark values that were manually reviewed; note that
         # they may become relevant if outliers are under scrutiny.
         -starts_with("J"), 
         # A continuous variable coded as a factor without documentation; may
         # be useful for pure prediction
         # -PCTFEEWAIV_R, 
         # Poorly documented variable with 99.5% of its values missing
         -WEEKLNGPCT
         )

# NAs in the dataset
missingvalues <- function(df) {
  NAs <- sum(sapply(df, \(x) sum(x == -8))) # Not applicable
  NRs <- sum(sapply(df, \(x) sum(x == -9))) # Not reported
  
  tibble(
    NAs = NAs, # Not applicable
    NRs = NRs, # Not reported
    perc.missing = (NAs + NRs) / prod(dim(df)) # % of missing values in the df
  )
}
missingvalues(rhfs)

# Missing values by interview type
rhfs |> 
  summarize(
    # pick(everything()) extracts a data frame of all non-grouping columns
    missingvalues(pick(everything())), 
    .by = OUTCOME
  )



# Handling known Trivially Missing values
# Certain values in the columns below can only exist if REGPAY is 1, so -9 is 
# wrongly assigned to them.
trivially.missing.regpay <- rhfs |> 
  mutate(id = row_number()) |> 
  filter( 
    REGPAY == -9 & 
      # In a given observation, if any of these columns contain a value other than
      # -8 or -9 return True.
      if_any(c(PMTAMT_R, PMTFREQ, RPIPRIN, RPIPRPINS, RPIPMI, RPIPRPTAX), \(x) !x %in% c(-8, -9))
    ) |>
  select(id, REGPAY, PMTAMT_R, PMTFREQ, RPIPRIN, RPIPRPINS, RPIPMI, RPIPRPTAX) |> 
  pull(id)

rhfs$REGPAY[trivially.missing.regpay] <- 1

# Same idea as with REGPAY
trivially.missing.ownothprop <- rhfs |> 
  mutate(id = row_number()) |> 
  filter( 
    OWNOTHPROP == -9 & 
      if_any(c(NUMOTHPROP, NUMOTHUNITS), \(x) !x %in% c(-8, -9))
    ) |>
  select(id, NUMOTHPROP, NUMOTHUNITS) |> 
  pull(id)

rhfs$OWNOTHPROP[trivially.missing.ownothprop] <- 1

# Same idea as with REGPAY
trivially.missing.rntappfeewaiv <- rhfs |> 
  mutate(id = row_number()) |> 
  filter( 
    RNTAPPFEEWAIV == -9 & 
      if_any(c(PCTFEEWAIV_R), \(x) !x %in% c(-8, -9))
    ) |>
  select(id, PCTFEEWAIV_R) |> 
  pull(id)

rhfs$OWNOTHPROP[trivially.missing.rntappfeewaiv] <- 1

# Ensuring that when CASHDWN is 2, CASHDWNAMT is always -9
rhfs |> 
  mutate(id = row_number()) |> 
  select(id, CASHDWN, CASHDWNAMT) |> 
  filter(CASHDWN == 2 & CASHDWNAMT != -9)

# If a CASHDWN payment wasn't made, then the CASHDWNAMT should be 0
rhfs$CASHDWNAMT <- ifelse(rhfs$CASHDWN == 2, 0, rhfs$CASHDWNAMT)

# Same idea as with CASHDWN/CASHDWNAMT
rhfs |> 
  mutate(id = row_number()) |> 
  select(id, WEEKLNG, WEEKLNGNUM) |> 
  filter(WEEKLNG == 2 & WEEKLNGNUM != -9)

rhfs$WEEKLNGNUM <- ifelse(rhfs$WEEKLNG == 2, 0, rhfs$WEEKLNGNUM)



# Evidence for MAR (missing at random) in MRKTVAL_R
df |> 
  mutate(
    mrktNA = MRKTVAL_R == -9
  ) |> 
  summarize(
    survey_mean(mrktNA), 
    .by = NUMCAT_R
  )

df |> 
  filter(MRKTVAL_R != -9) |> 
  summarize( 
    mean_mrktval = survey_mean(MRKTVAL_R), 
    median_mrktval = survey_median(MRKTVAL_R), 
    .by = NUMCAT_R 
  )
```


```{r EDA}

```


